version: "3.9"

services:
  flutter-vsc:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    command: /bin/sh -c "while sleep 1000; do :; done"
    secrets:
      - id_rsa
    volumes:
      - ../.vscode:/workspace/.vscode:cached
      - "~/.gitconfig:/etc/gitconfig"
    # env_file:
    #   - flutter/.flutter.env

secrets:
  id_rsa:
    file: ~/.ssh/id_rsa
